---

- name: copy the files used
  copy:
    src: "files"
    dest: "{{ config_location }}"

- name: Configure gogs 
  include_tasks: gogs.yml
  tags: gogs

- name: check if noobaa endpoint exists
  command: "{{ oc_location }} get pods noobaa-core-0 -n openshift-storage"
  register: noobaa_project_result
  ignore_errors: true
  changed_when: false
  tags: quay
  
- name: deploy openshift storage operator
  import_tasks: ./openshift-storage.yaml
  become: true
  when: noobaa_project_result is failed
  tags: quay

- name: Configure Quay 
  include_tasks: quay.yml
  tags: quay

- name: Configure OpenShift Pipelines 
  include_tasks: openshift-pipelines.yaml
  tags: pipelines

- name: Configure OpenShift Gitops 
  include_tasks: openshift-gitops.yaml
  tags: gitops

