---

- name: check if gogs project {{ gogs_project_name }} exists
  shell: "{{ oc_location }} get project {{ gogs_project_name }}"
  register: gogs_project_result
  ignore_errors: true
  changed_when: false
  tags: gogs

- name: create gogs project {{ gogs_project_name }}
  shell: "{{ oc_location }} new-project {{ gogs_project_name }} --display-name='quarkuscoffeeshop-cicd' --description='quarkuscoffeeshop-cicd project'"
  when: gogs_project_result is failed
  tags: gogs

- name: assign user as project admin
  shell: "{{ oc_location }} adm policy add-role-to-user admin {{ project_admin }} -n {{ gogs_project_name }}"
  ignore_errors: true
  when:
    - gogs_project_result is failed
    - project_admin is defined
    - project_admin is not none
    - project_admin|trim() != ""
  tags: gogs

- name: annotate gogs project {{ gogs_project_name }}
  shell: "{{ oc_location }} annotate --overwrite namespace {{ gogs_project_name }} {{ project_annotations }}"
  ignore_errors: true
  when:
    - gogs_project_result is failed
    - project_annotations is defined
    - project_annotations is not none
    - project_annotations|trim() != ""
  tags: gogs

- name: check if gogs exists
  shell: "{{ oc_location }} get service {{ gogs_service_name }} -n {{ gogs_project_name }}"
  register: install_gogs
  ignore_errors: true
  changed_when: false
  tags: gogs

- name: remove existing gogs if clean deploy requested
  shell: |
    {{ oc_location }} delete all,cm,pvc -l app={{ gogs_service_name }} -n {{ gogs_project_name }}
    {{ oc_location }} delete sa {{ gogs_service_name }} -n {{ gogs_project_name }}
  when:
    - install_gogs is succeeded
    - gogs_clean_deploy|bool
  tags: gogs

- import_tasks: deploy_gogs.yml
  when: gogs_clean_deploy|bool or install_gogs is failed

- name: wait for gogs sign_up to be ready
  uri:
    url: http://{{ gogs_urlprefix }}.apps.{{ domain }}/user/sign_up
    status_code: 200
  register: result
  until: result.status == 200
  retries: 10
  delay: 30
  tags: gogs

- name: create gogs admin user
  uri:
    url: http://{{ gogs_urlprefix }}.apps.{{ domain }}/user/sign_up
    method: POST
    # yamllint disable-line rule:line-length
    body: "user_name={{ gogs_admin_user }}&password={{ gogs_admin_password }}&&retype={{ gogs_admin_password }}&&email={{ gogs_admin_user }}@gogs.com"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 302,200
  tags: gogs

- name: check if user exists
  uri:
    url: http://{{ gogs_urlprefix }}.apps.{{ domain }}/api/v1/users/{{ gogs_user }}
    user: "{{ gogs_admin_user }}"
    password: "{{ gogs_admin_password }}"
    force_basic_auth: true
    status_code: 200,404
  register: user_result
  tags: gogs

- name: create gogs user
  uri:
    url: http://{{ gogs_urlprefix }}.apps.{{ domain }}/api/v1/admin/users
    method: POST
    # yamllint disable-line rule:line-length
    body: "{'login_name': '{{ gogs_user }}', 'username': '{{ gogs_user }}', 'email': '{{ gogs_user }}@gogs.com', 'password': '{{ gogs_user_password }}'}"
    body_format: json
    user: "{{ gogs_admin_user }}"
    password: "{{ gogs_admin_password }}"
    status_code: 200,201
    force_basic_auth: true
  when: user_result.status != 200
  tags: gogs

- name: generate gogs users
  uri:
    url: http://{{ gogs_urlprefix }}.apps.{{ domain }}/api/v1/admin/users
    method: POST
    body: "{'login_name': '{{ item }}', 'username': '{{ item }}', 'email': '{{ item }}@gogs.com', 'password': '{{ gogs_user_password }}'}"
    body_format: json
    user: "{{ gogs_admin_user }}"
    password: "{{ gogs_admin_password }}"
    status_code: 200,201
    force_basic_auth: true
  ignore_errors: true
  with_sequence: start=0 end={{ gogs_generate_user_count }} format="{{ user_format }}"
  when: gogs_generate_user_count|int >= 0
  tags: gogs

- name: create temporary git directory
  tempfile:
    state: directory
    path: "{{ config_location }}"
    prefix: "projects-git"
  register: git_dir
  tags: gogs

- name: create local repository to push to git
  command: |
    git clone {{ repo_url }}
  args:
    chdir: "{{ git_dir.path }}"
  tags: gogs

- name: check if repository exists in git for user "{{ item }}"
  uri:
    url: http://{{ gogs_urlprefix }}.apps.{{ domain }}/api/v1/repos/{{ item }}/{{ reponame_local }}
    user: "{{ item }}"
    password: "{{ gogs_user_password }}"
    force_basic_auth: true
    status_code: 200,404
  register: repo_result
  with_sequence: start=0 end={{ gogs_generate_user_count }} format="{{ user_format }}"
  when: gogs_generate_user_count|int >= 0
  tags: gogs

- name: create git repository for user "{{ item }}"
  uri:
    url: http://{{ gogs_urlprefix }}.apps.{{ domain }}/api/v1/user/repos
    method: POST
    body: '{"name": "{{ reponame_local }}", "private": false}'
    body_format: json
    user: "{{ item }}"
    password: "{{ gogs_user_password }}"
    status_code: 200,201
    force_basic_auth: true
  with_sequence: start=0 end={{ gogs_generate_user_count }} format="{{ user_format }}"
  when: gogs_generate_user_count|int >= 0 and repo_result.status != 200'
  tags: gogs

- name: remove git metadata
  shell: |
    rm -fr .git
  args:
    chdir: "{{ git_dir.path }}/{{ reponame }}"
  tags: gogs

- name: create new git repo
  shell: |
    rm -fr .git || true
    git init .
    git add *
    git commit -am "Initial checkin"
  args:
    chdir: "{{ git_dir.path }}/{{ reponame }}"
  tags: gogs

- name: push catalog to git repository in Gogs for user "{{ item }}"
  # yamllint disable rule:line-length
  shell: |
    git remote add {{ item }} http://{{ item }}:{{ gogs_user_password }}@{{ gogs_urlprefix }}.apps.{{ domain }}/{{ item }}/{{ reponame_local }}.git
    git config --local user.email "{{ item }}@example.com"
    git config --local user.name "{{ item }}"
    git push -f --all {{ item }}
  # yamllint enable rule:line-length
  args:
    chdir: "{{ git_dir.path }}/{{ reponame }}"
  with_sequence: start=0 end={{ gogs_generate_user_count }} format="{{ user_format }}"
  when: gogs_generate_user_count|int >= 0 and repo_result.status != 200'
  tags: gogs

