- name: login as super user with token on OpenShift 4
  shell: "oc login --token={{ openshift_token }}  --server={{ openshift_url }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
  when:
   - openshift_token is defined
   - openshift_token is not none
   - openshift_token|trim() != ""
  ignore_errors: no

- name: Create new project for quarkus-cafe
  command: "oc new-project {{ project_namespace }}"
  register: create_project_result
  ignore_errors: yes
  when: not delete_deployment

- name: Switch to project for quarkus-cafe
  command:  "oc project {{ project_namespace }}"
  register: switch_project_result