---
# tasks file for quarkus-cafe-demo-role
- name: Configure settings environment using OpenShift token
  block:
    - name: Login Cluster
      include_tasks: login-to-cluster.yml

    - name: Create Quarkus project 
      include_tasks: create-project.yml

    - name: AMQ Streams installation
      include_tasks: amq-streams-install.yml
      when: not skip_amq_install

    - name: MongoDB Operator installation
      include_tasks: mongodb-operator-install.yml
      when: not skip_mongodb_operator_install
  when: not use_kubeconfig | bool
