
- name: Create OpenShift gitops OperatorGroup
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'openshift-gitops.yaml.j2') }}"
  tags: gitops

- name: Wait for GitOps CRD to exist
  k8s_facts:
    api_version: "apiextensions.k8s.io/v1beta1"
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop: "{{ ocp4_edge_gitops_expected_crds }}"
  register: crds
  until: crds.resources|length > 0
  retries: 30
  delay: 10
  tags: gitops

- name: Add ClusterRoleBinding to the openshift-gitops-controller
  k8s:
    state: present
    definition: "{{ lookup('template', 'gitops-rb.yml.j2') }}"
  tags: gitops


- name: Get ArgoCD route
  k8s_info:
    kind: Route
    api_version: route.openshift.io/v1
    name: openshift-gitops-server
    namespace: openshift-gitops
  register: r_argo_route
  retries: 10
  delay: 20
  until:
    - r_argo_route.resources[0].spec.host is defined
  tags: gitops

- name: Get argocd password
  k8s_info:
    kind: Secret
    api_version: /v1
    name: openshift-gitops-cluster
    namespace: openshift-gitops
  register: r_argopass
  tags: gitops

- name: Store central route as a fact
  set_fact:
    f_argopass: "{{ r_argopass.resources[0].data['admin.password'] }}"
  tags: gitops

# Set up an ArgoCD route as an cm/env to use in tkn Pipelines
- name: Add CM for ArgoCD env
  k8s:
    state: present
    definition: "{{ lookup('template', 'gitops-env-cm.yaml.j2') }}"
  tags: gitops

# Define ArgoCD admin creds to use in tkn Pipelines
- name: Add Secrets for ArgoCD env
  k8s:
    state: present
    definition: "{{ lookup('template', 'gitops-env-secret.yaml.j2') }}"
  tags: gitops