---
- name: copy the files used
  copy:
    src: "files"
    dest: "{{ config_location }}"
  tags: quay

- name: Get OpenShift storage operator version
  shell: |
    {{ oc_location }}  describe packagemanifests  ocs-operator -n openshift-marketplace | grep Version: |  grep {{ oc_version }}  | awk '{print $2}'
  register: operator_version_check
  become: no
  tags: quay

- name: setting openshift-storage-operator version
  set_fact:
    ocs_starting_csv: "{{ operator_version_check.stdout }}"
  tags: quay

- name: deploy the openshift storage operator
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'openshift-storage-operator.yaml.j2') }}"
  tags: quay

- name: Pause for 120 seconds for pods to download 
  pause:
    seconds: 120
  tags: quay

- name: Waiting for openshift storage operator
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: openshift-storage
    label_selectors:
      - name = ocs-operator
    field_selectors:
      - status.phase=Running
  register: r_storage_status
  retries: 120
  delay: 15
  until: r_storage_status.resources | list | length == 1
  tags: quay

- name: displaying openshift storage operator  deployment status
  debug:
    var: r_storage_status.resources[0].status.phase
  ignore_errors: false
  tags: quay

- name: deploy the quay-datastore noobaa
  command: "{{ oc_location }} create -f quay-datastore.noobaa.yaml"
  args:
    chdir: "{{ config_location }}/files"
  tags: quay

- name: Waiting for noobaa-db-pg-0
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: openshift-storage
    label_selectors:
      - app = noobaa
    field_selectors:
      - status.phase=Running
  register: r_noobadb
  retries: 120
  delay: 15
  until: r_noobadb.resources | list | length == 1
  tags: quay