- name: Copying over quarkus-cafe-web application
  template:
    src: templates/quarkus-cafe-web.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-web.yaml"
    owner: root
    group: root
    mode: 0666
  when: not skip_quarkus_cafe_web

- name: Create quarkus-cafe-web instance
  command: "oc create -f {{ config_location }}/quarkus-cafe-web.yaml"
  when: not delete_deployment

- name: Waiting for quarkus-cafe-web build to complete
  shell: |
    set -o pipefail && oc get pods  | grep Completed | grep quarkus-cafe-web | wc -l
  register: install_status
  when: not delete_deployment
  until: "'2' in install_status.stdout"
  retries: 120
  delay: 15
  args:
    executable: /bin/bash

- name: Waiting for quarkus-cafe-web deployment
  shell: |
    set -o pipefail && oc get pods  | grep Running | grep quarkus-cafe-web | wc -l
  register: install_status
  when: not delete_deployment
  until: "'1' in install_status.stdout"
  retries: 60
  delay: 15

- name: Delete quarkus-cafe-web instance
  command: "oc delete -f {{ config_location }}/quarkus-cafe-web.yaml"
  ignore_errors: yes
  when: delete_deployment
  args:
    executable: /bin/bash

