- name: Create mongodb instance
  command: "/usr/local/bin/oc new-app --name=mongodb --template=mongodb-ephemeral -e MONGODB_USER=mongodb -e MONGODB_PASSWORD=mongodb -e MONGODB_DATABASE=cafedb -e MONGODB_ADMIN_PASSWORD=mongodb"
  when: not delete_deployment|bool

- name: Waiting for mongodb build to complete
  shell: |
   set -o pipefail &&  /usr/local/bin/oc get pods  | grep Completed | grep mongodb | wc -l
  register: install_status
  when: not delete_deployment|bool
  until: "'1' in install_status.stdout"
  retries: 120
  delay: 15
  args:
    executable: /bin/bash

- name: Waiting for mongodb deployment
  shell: |
    set -o pipefail && /usr/local/bin/oc get pods  | grep Running | grep mongodb | wc -l
  register: install_status
  when: not delete_deployment|bool
  until: "'1' in install_status.stdout"
  retries: 60
  delay: 15
  args:
    executable: /bin/bash

- name: Delete mongodb instance
  command: "/usr/local/bin/oc delete all --selector app=mongodb"
  ignore_errors: yes
  when: delete_deployment|bool

- name: Delete mongodb instance
  command: "/usr/local/bin/oc delete secret mongodb"
  ignore_errors: yes
  when: delete_deployment|bool

- name: Copying over quarkus-cafe-core application
  template:
    src: templates/s2i/quarkus-cafe-core.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-core.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_owner }}"
    mode: 0666
  when: not skip_quarkus_cafe_core  and  deployment_method == "s2i"

- name: Copying over quarkus-cafe-core application
  template:
    src: templates/docker/quarkus-cafe-core.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-core.yaml"
    owner: "{{ default_owner }}"
    group: "{{ default_owner }}"
    mode: 0666
  when: not skip_quarkus_cafe_core  and  deployment_method == "docker"

- name: Create quarkus-cafe-core instance
  command: "/usr/local/bin/oc create -f {{ config_location }}/quarkus-cafe-core.yaml"
  when: not delete_deployment|bool

- name: Waiting for quarkus-cafe-core build to complete
  shell: |
    set -o pipefail && /usr/local/bin/oc get pods  | grep Completed | grep quarkus-cafe-core | wc -l
  register: install_status
  when: not delete_deployment|bool  and  deployment_method == "s2i"
  until: "'2' in install_status.stdout"
  retries: 120
  delay: 15
  args:
    executable: /bin/bash

- name: Waiting for quarkus-cafe-core deployment
  shell: |
    set -o pipefail && /usr/local/bin/oc get pods  | grep Running | grep quarkus-cafe-core | wc -l
  register: install_status
  when: not delete_deployment|bool
  until: "'1' in install_status.stdout"
  retries: 60
  delay: 15
  args:
    executable: /bin/bash

- name: Delete quarkus-cafe-core instance
  command: "/usr/local/bin/oc delete -f {{ config_location }}/quarkus-cafe-core.yaml"
  ignore_errors: yes
  when: delete_deployment|bool
