- name: Copying over quarkus-cafe-barista application
  template:
    src: templates/s2i/quarkus-cafe-barista.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-barista.yaml"
    owner: root
    group: root
    mode: 0666
  when: not skip_quarkus_cafe_barista and deployment_method == "s2i"

- name: Copying over quarkus-cafe-barista application
  template:
    src: templates/docker/quarkus-cafe-barista.yaml.j2
    dest:  "{{ config_location }}/quarkus-cafe-barista.yaml"
    owner: root
    group: root
    mode: 0666
  when: not skip_quarkus_cafe_barista and deployment_method == "docker"

- name: Create quarkus-cafe-barista instance
  command: "oc create -f {{ config_location }}/quarkus-cafe-barista.yaml"
  when: not delete_deployment|bool

- name: Waiting for quarkus-cafe-barista build to complete
  shell: |
     set -o pipefail && oc get pods  | grep Completed | grep quarkus-cafe-barista | wc -l
  register: install_status
  when: not delete_deployment|bool and deployment_method == "s2i"
  until: "'2' in install_status.stdout"
  retries: 120
  delay: 15
  args:
    executable: /bin/bash

- name: Waiting for quarkus-cafe-barista deployment
  shell: |
     set -o pipefail && oc get pods  | grep Running | grep quarkus-cafe-barista | wc -l
  register: install_status
  when: not delete_deployment|bool
  until: "'1' in install_status.stdout"
  retries: 60
  delay: 15
  args:
    executable: /bin/bash

- name: Delete quarkus-cafe-barista instance
  command: "oc delete -f {{ config_location }}/quarkus-cafe-barista.yaml"
  ignore_errors: yes
  when: delete_deployment|bool

