- name: Remove OpenShift Pipelines OperatorGroup
  kubernetes.core.k8s:
    state: absent
    namespace: openshift-operators
    definition: "{{ lookup('template', 'openshift-pipelines.yaml.j2') }}"
  ignore_errors: true
  tags: always

- name: Remove OpenShift gitops OperatorGroup
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'openshift-gitops.yaml.j2') }}"
  ignore_errors: true
  tags: always


- name: delete QuayRegistry quayecosystem
  command: oc delete QuayRegistry quayecosystem -n "{{ quay_project_name }}"
  ignore_errors: true
  tags: always

- name: delete quay crd
  command: oc delete crd quayecosystems.redhatcop.redhat.io -n "{{ quay_project_name }}"
  ignore_errors: true
  tags: always

- name: delete openshift-storage.noobaa.io storage class
  command:  oc delete sc openshift-storage.noobaa.io -n "{{ quay_project_name }}"
  ignore_errors: true
  tags: always

- name: delete  storageclusters.ocs.openshift.io crd 
  command:  oc delete crd  storageclusters.ocs.openshift.io -n "{{ quay_project_name }}"
  ignore_errors: true
  tags: always

- name: delete  remaining csvs
  command:  oc delete csv $(oc get csv | awk '{print $1}') -n openshift-operators
  ignore_errors: true
  tags: always

- name: delete openshift-gitops project
  command: oc delete project openshift-gitops
  ignore_errors: true
  tags: always


- name: delete openshift-storage project
  command: oc delete project openshift-storage
  ignore_errors: true
  tags: always

- name: delete development project
  command: "oc delete project {{ development_project }}"
  ignore_errors: true
  tags: always

- name: delete homeoffice project
  command: "oc delete project {{ homeoffice_project }}"
  ignore_errors: true
  tags: always

- name: delete quay-enterprise project
  command: "oc delete project {{ quay_project_name }}"
  ignore_errors: true
  tags: always